/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-04-22 07:12:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class get_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1712041483651L));
    _jspx_dependants.put("jar:file:/C:/Users/vip/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springFinal/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1712041483652L));
    _jspx_dependants.put("jar:file:/C:/Users/vip/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springFinal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1713767619989L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>SB Admin 2 - Tables</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"../resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"../resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this page -->\r\n");
      out.write("    <link href=\"../resources/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">SB Admin <sup>2</sup></div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Dashboard -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("                    <span>Dashboard</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                Interface\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-cog\"></i>\r\n");
      out.write("                    <span>Components</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"buttons.html\">Buttons</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">Cards</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-wrench\"></i>\r\n");
      out.write("                    <span>Utilities</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Utilities:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-border.html\">Borders</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                Addons\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapsePages\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("                    <span>Pages</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"login.html\">Login</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"register.html\">Register</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\r\n");
      out.write("                        <div class=\"collapse-divider\"></div>\r\n");
      out.write("                        <h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Charts -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-chart-area\"></i>\r\n");
      out.write("                    <span>Charts</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Tables -->\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>Tables</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.uploadResult {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		background-color: gray;\r\n");
      out.write("	}\r\n");
      out.write("	.uploadResult ul {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-flow: row;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	/* p543 수정 */ \r\n");
      out.write("	.uploadResult ul li {\r\n");
      out.write("		list-style: none;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		align-content: center;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.uploadResult ul li img {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.uploadResult ul li span {\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	.bigPictureWrapper {\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		display: none;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		top: 0%;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		background-color: gray;\r\n");
      out.write("		z-index: 100;\r\n");
      out.write("		background: rgba(255,255,255,0.5)\r\n");
      out.write("	}\r\n");
      out.write("	.bigPicture {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	.bigPicture img {\r\n");
      out.write("		width: 600px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/re.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("const showImage=(fileCallPath)=>{\r\n");
      out.write("	console.log(\"fileCallPath\",fileCallPath)\r\n");
      out.write("	//alert(fileCallPath)\r\n");
      out.write("	// p544\r\n");
      out.write("	 $(\".bigPictureWrapper\").css(\"display\",\"flex\").show();\r\n");
      out.write("     $(\".bigPicture\").html(\"<img src='/display?fileName=\" +fileCallPath+\"'>\")\r\n");
      out.write("    		.animate({width:'100%',height:'100%'},1000);\r\n");
      out.write("}\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		//p570\r\n");
      out.write("		(function(){\r\n");
      out.write("			var bno = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("			$.getJSON(\"/board/getAttachList\",{bno}, (arr)=>{console.log(arr)\r\n");
      out.write("				var str=\"\"\r\n");
      out.write("				$(arr).each(function(idx, obj){ //p525\r\n");
      out.write("					if(obj.fileType) { // 이미지가 맞으면 아래 실행\r\n");
      out.write("						console.log(\"이미지 \")\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath+ \"/s_\"+obj.uuid+\"_\"+obj.fileName)\r\n");
      out.write("						var originPath = obj.uploadPath+ \"/\"+obj.uuid+\"_\"+obj.fileName\r\n");
      out.write("						originPath = originPath.replace(new RegExp(/\\\\/g), \"/\")  // \"\\\\\" => \"/\"  로 대체한다 (global)\r\n");
      out.write("						str+= \"<li data-path='\"+obj.uploadPath+\"'data-uuid='\"+obj.uuid+\"' data-fileName='\"+obj.fileName+\"'data-type='\"+obj.image+\"'\"\r\n");
      out.write("						str+= \"><div><span>\"+obj.fileName+\"</span><button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='image' \"\r\n");
      out.write("						str+= \"class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\"\r\n");
      out.write("						str+= \"<img src='/display?fileName=\" + fileCallPath +\"'></div></li>\"\r\n");
      out.write("					} else { // 이미지가 아니면 아래 실행\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath+ \"/\"+obj.uuid+\"_\"+obj.fileName)\r\n");
      out.write("						var fileLink = fileCallPath.replace(new RegExp(/\\\\/g), \"/\")\r\n");
      out.write("						str+= \"<li data-path='\"+obj.uploadPath+\"'data-uuid='\"+obj.uuid+\"' data-fileName='\"+obj.fileName+\"'data-type='\"+obj.image+\"'\"\r\n");
      out.write("						str+= \"><div><span>\"+obj.fileName+\"</span><button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='file' \"\r\n");
      out.write("						str+= \"class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button></br>\"\r\n");
      out.write("						str+= \"<img src='/resources/img/attach.jpg'></div></li>\"\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("				$(\".uploadResult ul\").append(str)\r\n");
      out.write("			\r\n");
      out.write("			})\r\n");
      out.write("		})()//end function\r\n");
      out.write("		$(\".uploadResult\").on(\"click\",\"li\", function(e) {\r\n");
      out.write("			console.log(\"이미지 보기\")\r\n");
      out.write("			var liObj = $(this)\r\n");
      out.write("			var path= encodeURIComponent(liObj.data(\"path\")+\"/\" +liObj.data(\"uuid\") +\"_\" +liObj.data(\"filename\"))\r\n");
      out.write("			console.log(\"path: \" , path)\r\n");
      out.write("			console.log(\"type: \" , liObj.data('type')) //type=true\r\n");
      out.write("            if(liObj.data('type')) showImage(path.replace(new RegExp(/\\\\/g),\"/\"))\r\n");
      out.write("			else self.location =\"/download?fileName=\"+path\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		}) // uploadResult click\r\n");
      out.write("		console.log('replyService',replyService)\r\n");
      out.write("		const showList=(page)=>{\r\n");
      out.write("			var replyUL=$(\".chat\")	\r\n");
      out.write("			replyService.getList({bno:bnoValue, page:page||1},\r\n");
      out.write("				({replyCnt, list})=>{\r\n");
      out.write("					console.log(\"list: \", replyCnt, list)\r\n");
      out.write("					if(page == -1) { // pageDTO => board (자바버전) => javascript 버전\r\n");
      out.write("						pageNum = Math.ceil(replyCnt/10.0) // 무조건 올림\r\n");
      out.write("						showList(pageNum)\r\n");
      out.write("						return\r\n");
      out.write("					}\r\n");
      out.write("					var str=\"\"\r\n");
      out.write("					if(list ==null || list.length ==0) {\r\n");
      out.write("						replyUL.html(\"\")\r\n");
      out.write("						return ;\r\n");
      out.write("					}\r\n");
      out.write("					var len = list.length\r\n");
      out.write("					for(var i=0; i<len || 0; i++){\r\n");
      out.write("						str+= \"<li class='left clearfix' data-rno='\" + list[i].rno +\"'>\"\r\n");
      out.write("						str+= \"  <div><div class='header'><strong class='primary-font'>\" + list[i].replyer +\"</strong>\"\r\n");
      out.write("						str+= \"   <small calss='pull-right text-muted'>\" + replyService.displayTime(list[i].replyDate) +\"</small></div>\"\r\n");
      out.write("						str+= \"   <p>\" + list[i].reply +\"</p></div></li>\"\r\n");
      out.write("					}\r\n");
      out.write("					replyUL.html(str)\r\n");
      out.write("					\r\n");
      out.write("					showReplyPage(replyCnt)\r\n");
      out.write("				} // lambda 함수 (list)=> {}, getList 의  두번째 인자(성공하면 호출되는 callback)		\r\n");
      out.write("			) // getList\r\n");
      out.write("		} // showList\r\n");
      out.write("		\r\n");
      out.write("		var pageNum = 1\r\n");
      out.write("		var replyPageFooter = $(\".panel-footer\")\r\n");
      out.write("		const showReplyPage=(replyCnt)=>{ // 여기 복사해서 p440 으로 변경 (page 단위 처리)\r\n");
      out.write("			var endNum = Math.ceil(pageNum /10.0) * 10\r\n");
      out.write("			var startNum = endNum - 9\r\n");
      out.write("			\r\n");
      out.write("			var prev = startNum != 1\r\n");
      out.write("			var next = false\r\n");
      out.write("			\r\n");
      out.write("			if(endNum * 10 >= replyCnt) endNum = Math.ceil(replyCnt/10.0)\r\n");
      out.write("			if(endNum * 10 < replyCnt) next = true\r\n");
      out.write("			var str = \"<ul class='pagination pull-right'>\"\r\n");
      out.write("			if(prev) {\r\n");
      out.write("				str+= \"<li class='page-item'><a class='page-link' href='\"+ (startNum -1) +\"'>이전</a></li>\"\r\n");
      out.write("			}\r\n");
      out.write("			for(var i=startNum; i<=endNum; i++) {\r\n");
      out.write("				var active = pageNum == i? \"active\":\"\"\r\n");
      out.write("				str+= \"<li class='page-item \"+ active + \" '><a class='page-link' href='\"+ i +\"'>\"+ i +\"</a></li>\"\r\n");
      out.write("			}\r\n");
      out.write("			if(next) {\r\n");
      out.write("				str+= \"<li class='page-item'><a class='page-link' href='\"+(endNum+1)+\"'>다음</a></li>\"\r\n");
      out.write("			}\r\n");
      out.write("			str+=\"</ul></div>\"\r\n");
      out.write("			console.log(str)\r\n");
      out.write("			replyPageFooter.html(str)\r\n");
      out.write("		} // showReplyPage\r\n");
      out.write("		\r\n");
      out.write("		replyPageFooter.on(\"click\",\"li a\", function(e){\r\n");
      out.write("			e.preventDefault()\r\n");
      out.write("			console.log(\"페이지를 클릭\")\r\n");
      out.write("			\r\n");
      out.write("			var targetPageNum = $(this).attr(\"href\")\r\n");
      out.write("			console.log(\"targetPageNum : \"+ targetPageNum)\r\n");
      out.write("			pageNum = targetPageNum\r\n");
      out.write("			showList(pageNum)\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"JS TEST.....\")\r\n");
      out.write("		var bnoValue = '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("		console.log(\"bno: \" + bnoValue)\r\n");
      out.write("		\r\n");
      out.write("		//showList(1)\r\n");
      out.write("		showList(-1) // 마지막 페이지이면 -1 로 설정 (p438) 하단\r\n");
      out.write("		\r\n");
      out.write("		var modal=$(\".modal\")\r\n");
      out.write("		var modalInputReply = modal.find(\"input[name='reply']\")\r\n");
      out.write("		var modalInputReplyer = modal.find(\"input[name='replyer']\")\r\n");
      out.write("		var modalInputReplyDate = modal.find(\"input[name='replyDate']\")\r\n");
      out.write("		\r\n");
      out.write("		var modalModBtn = $(\"#modalModBtn\")\r\n");
      out.write("		var modalRemoveBtn = $(\"#modalRemoveBtn\")\r\n");
      out.write("		var modalRegisterBtn = $(\"#modalRegisterBtn\")\r\n");
      out.write("		\r\n");
      out.write("		$(\"#addReplyBtn\").click(function(e){\r\n");
      out.write("			modal.find(\"input\").val(\"\")\r\n");
      out.write("			modalInputReplyDate.closest(\"div\").hide() // 가장 가까운 div 를 찾아 감춘다\r\n");
      out.write("			modal.find(\"button[id !='modalCloseBtn']\").hide() // id 가 modalCloseBtn 이 아닌것을 찾아 감춘다\r\n");
      out.write("			\r\n");
      out.write("			modalRegisterBtn.show();\r\n");
      out.write("			$(\".modal\").modal(\"show\")\r\n");
      out.write("		})\r\n");
      out.write("		//p423\r\n");
      out.write("		modalRegisterBtn.click(function(e){\r\n");
      out.write("			var reply = {\r\n");
      out.write("					reply: modalInputReply.val(),\r\n");
      out.write("					replyer:modalInputReplyer.val(),\r\n");
      out.write("					bno:bnoValue\r\n");
      out.write("			}\r\n");
      out.write("			console.log(\"댓글 등록: \", reply)\r\n");
      out.write("			replyService.add(reply, (result)=>{\r\n");
      out.write("				alert(result)\r\n");
      out.write("				modal.find(\"input\").val(\"\")\r\n");
      out.write("				modal.modal(\"hide\")\r\n");
      out.write("				\r\n");
      out.write("				showList(1)\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		//p425\r\n");
      out.write("		$(\".chat\").on(\"click\",\"li\", function(e){\r\n");
      out.write("			console.log($(this))\r\n");
      out.write("			// 해당이 아닌 제일 위에것\r\n");
      out.write("			var rno= $(this).data(\"rno\")\r\n");
      out.write("			console.log(rno)\r\n");
      out.write("			replyService.get(rno, (reply)=>{ // 데이터 하나 조회하여 modal의 input 태그 에 출력함\r\n");
      out.write("				modalInputReply.val(reply.reply)\r\n");
      out.write("				modalInputReplyer.val(reply.replyer)\r\n");
      out.write("				modalInputReplyDate.val(replyService.displayTime(reply.replyDate)).attr(\"readonly\", \"readonly\")\r\n");
      out.write("				modal.data(\"rno\", reply.rno)\r\n");
      out.write("				\r\n");
      out.write("				modal.find(\"button[id !='modalCloseBtn']\").hide()\r\n");
      out.write("				modalModBtn.show()\r\n");
      out.write("				modalRemoveBtn.show()\r\n");
      out.write("				\r\n");
      out.write("				$(\".modal\").modal(\"show\")\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		//p426 수정\r\n");
      out.write("		modalModBtn.click(function(e){\r\n");
      out.write("			console.log(\"수정 버튼이 눌렸어요\")\r\n");
      out.write("			var reply={rno:modal.data(\"rno\"), reply: modalInputReply.val()}\r\n");
      out.write("			console.log(\"reply: \",reply)\r\n");
      out.write("			replyService.update(reply, (result)=>{\r\n");
      out.write("				alert(result)\r\n");
      out.write("				modal.modal(\"hide\")\r\n");
      out.write("				showList(1)\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		//p427 삭제\r\n");
      out.write("		modalRemoveBtn.click(function(e){\r\n");
      out.write("			console.log(\"삭제 버튼이 눌렸어요\")\r\n");
      out.write("			var rno = modal.data(\"rno\")\r\n");
      out.write("			console.log(\"rno: \", rno)\r\n");
      out.write("			replyService.remove(rno, (result)=>{\r\n");
      out.write("				alert(result)\r\n");
      out.write("				modal.modal(\"hide\")\r\n");
      out.write("				showList(1)\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		// 수정, 추가는 정보를 담아서 보내야 되니까 객체로 담아서 보내고\r\n");
      out.write("		// 삭제, 조회, 댓글삭제는 rno 만 보내면 되는데\r\n");
      out.write("		// 댓글 조회 같은 경우는 bno 와 같이 보내야 하니 bno, rno 같이 보내야 한다\r\n");
      out.write("		var operForm =$(\"form\")\r\n");
      out.write("		$(\"button[data-oper='modify']\").click(function(e){\r\n");
      out.write("			e.preventDefault()\r\n");
      out.write("			console.log($(this).attr(\"data-oper\"))\r\n");
      out.write("			var bno=$(\"#form-control\").eq(0).val()\r\n");
      out.write("			operForm.attr(\"action\", \"/board/modify?bno=\"+bno).attr(\"method\",\"get\").submit();\r\n");
      out.write("		})\r\n");
      out.write("		$(\"button[data-oper='list']\").click(function(e){\r\n");
      out.write("			e.preventDefault()\r\n");
      out.write("			console.log($(this).attr(\"data-oper\"))\r\n");
      out.write("			operForm.attr(\"action\", \"/board/list\")\r\n");
      out.write("				.empty()\r\n");
      out.write("				.attr(\"method\",\"get\").submit();\r\n");
      out.write("			// empty => form 태그의 내용을 다 비워라\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("                <!-- Begin Page Content -->\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Page Heading -->\r\n");
      out.write("                    <h1 class=\"h3 mb-2 text-gray-800\" style=\"text-align:center\">게시글 조회</h1>\r\n");
      out.write("                    <p class=\"mb-4\">DataTables is a third party plugin that is used to generate the demo table below.\r\n");
      out.write("                        For more information about DataTables, please visit the <a target=\"_blank\"\r\n");
      out.write("                            href=\"https://datatables.net\">official DataTables documentation</a>.</p>\r\n");
      out.write("\r\n");
      out.write("                    <!-- DataTables Example -->\r\n");
      out.write("                    <div class=\"card shadow mb-4\" style=\"text-align:center\">\r\n");
      out.write("                        <div class=\"card-header py-3\">\r\n");
      out.write("                            <h6 class=\"m-0 font-weight-bold text-primary\">게시글 조회</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                        	<form action=\"#\" role=\"form\" method=\"post\">\r\n");
      out.write("                        	    <div class=\"form-group\">\r\n");
      out.write("                        			<label>번호</label> <input class=\"form-control\" name='bno' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' readonly/>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		<div class=\"form-group\">\r\n");
      out.write("                        			<label>제목</label> <input class=\"form-control\" name='title' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' readonly/>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		<div class=\"form-group\">\r\n");
      out.write("                        			<label>내용</label>\r\n");
      out.write("                        			<textarea class=\"form-control\" rows=\"3\" name='content' readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		<div class=\"form-group\">\r\n");
      out.write("                        			<label>작성자</label> <input class=\"form-control\" name='writer' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' readonly/>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		<button data-oper=\"modify\" class=\"btn btn-primary\">수정하러가기</button>\r\n");
      out.write("                        		<button data-oper=\"list\" class=\"btn btn-info\">목록으로이동</button>\r\n");
      out.write("                        		<!-- p345 4개의 정보를 hidden 으로 유지되도록 처리 -->\r\n");
      out.write("                        		<form id=\"operForm\" action=\"/board/modify\">\r\n");
      out.write("                        			<input type=\"hidden\" id=\"bno\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        			<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        			<input type=\"hidden\" name=\"amount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        			<input type=\"hidden\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                        			<input type=\"hidden\" name=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("                       			</form>\r\n");
      out.write("                        	</form>\r\n");
      out.write("                        </div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-12\">\r\n");
      out.write("								<div class=\"panel-heading\">\r\n");
      out.write("									<div class=\"panel-body\">\r\n");
      out.write("										<div class=\"uploadResult\">\r\n");
      out.write("											<ul>\r\n");
      out.write("											\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"bigPictureWrapper\">\r\n");
      out.write("							<div class=\"bigPicture\">\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                        	<div class=\"col-lg-12\">\r\n");
      out.write("                        		<div class=\"panel-heading\">\r\n");
      out.write("                        			<i class=\"fa fa-comments fa-fw\">댓글</i>\r\n");
      out.write("                        			<button id='addReplyBtn' class='btn btn-primary btn-xs pull-right'>댓글 등록</button>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		<div class=\"panel-body\">\r\n");
      out.write("                        			<ul class=\"chat\">\r\n");
      out.write("                        				<!--  댓글 시작 -->\r\n");
      out.write("                        				<li class=\"left clearfix\" data-rno=\"1\">\r\n");
      out.write("                        					<div>\r\n");
      out.write("                        						<div class=\"header\">\r\n");
      out.write("                        							<strong class=\"primary-font\">user00</strong>\r\n");
      out.write("                        							<small class=\"pull-right text-muted\">2023-03-14</small>\r\n");
      out.write("                        						</div>\r\n");
      out.write("                        						<p>참 잘했어요</p>\r\n");
      out.write("                        					</div>\r\n");
      out.write("                        				</li>\r\n");
      out.write("                        			</ul>\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        		\r\n");
      out.write("                        		<div class=\"panel-footer\">\r\n");
      out.write("                        		\r\n");
      out.write("                        		</div>\r\n");
      out.write("                        	</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("<!-- Button trigger modal -->\r\n");
      out.write("<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("  Launch demo modal\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"myModalLabel\">댓글 Modal</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("        	<label>댓글</label>\r\n");
      out.write("        	<input class=\"form-control\" name=\"reply\" value=\"신규 댓글\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("        	<label>작성자</label>\r\n");
      out.write("        	<input class=\"form-control\" name=\"replyer\" value=\"댓글작성자\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("        	<label>입력일</label>\r\n");
      out.write("        	<input class=\"form-control\" name=\"replyDate\" value=\"댓글작성일\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button id=\"modalModBtn\" type=\"button\" class=\"btn btn-warning\">수정</button>\r\n");
      out.write("        <button id=\"modalRemoveBtn\" type=\"button\" class=\"btn btn-danger\">삭제</button>\r\n");
      out.write("        <button id=\"modalRegisterBtn\" type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">등록</button>\r\n");
      out.write("        <button id=\"modalCloseBtn\" type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; Your Website 2020</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("<!--     <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">Ã</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("<!--     <script src=\"../resources/vendor/jquery/jquery.min.js\"></script> -->\r\n");
      out.write("    <script src=\"../resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"../resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"../resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"../resources/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"../resources/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"../resources/js/demo/datatables-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!--  êµì¬ p235 ì°½ì í¬ê¸°ë¥¼ ì¤ì¼ë ëª¨ë°ì¼ ííë¡ ì íëì´ì¼ í©ëë¤. -->\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$('#dataTables-example').DataTable({\r\n");
      out.write("				responsive: true\r\n");
      out.write("			});\r\n");
      out.write("			$(\".sidebar-nav\")\r\n");
      out.write("				.attr(\"class\",\"sidebar-nav navbar-collapse collapse\")\r\n");
      out.write("				.attr(\"aria-expanded\",'false')\r\n");
      out.write("				.attr(\"style\",\"height:1px\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/board/get.jsp(66,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/board/get.jsp(171,18) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
