/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-04-22 06:58:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1712041483651L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1712041483652L));
    _jspx_dependants.put("jar:file:/C:/Users/vip/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springFinal/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1713767619989L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>SB Admin 2 - Tables</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"../resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"../resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this page -->\r\n");
      out.write("    <link href=\"../resources/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">SB Admin <sup>2</sup></div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Dashboard -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"index.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("                    <span>Dashboard</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                Interface\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseTwo\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-cog\"></i>\r\n");
      out.write("                    <span>Components</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Components:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"buttons.html\">Buttons</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"cards.html\">Cards</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Utilities Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapseUtilities\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-wrench\"></i>\r\n");
      out.write("                    <span>Utilities</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingUtilities\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Custom Utilities:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-color.html\">Colors</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-border.html\">Borders</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-animation.html\">Animations</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"utilities-other.html\">Other</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                Addons\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"#\" data-toggle=\"collapse\" data-target=\"#collapsePages\"\r\n");
      out.write("                    aria-expanded=\"true\" aria-controls=\"collapsePages\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("                    <span>Pages</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <h6 class=\"collapse-header\">Login Screens:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"login.html\">Login</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"register.html\">Register</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"forgot-password.html\">Forgot Password</a>\r\n");
      out.write("                        <div class=\"collapse-divider\"></div>\r\n");
      out.write("                        <h6 class=\"collapse-header\">Other Pages:</h6>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"404.html\">404 Page</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"blank.html\">Blank Page</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Charts -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-chart-area\"></i>\r\n");
      out.write("                    <span>Charts</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Tables -->\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>Tables</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	var formObj= $(\"form[role='form']\")\r\n");
      out.write("        $(\"button[type='submit']\").click(function(e){\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            console.log('전송 버튼이 눌렸어요')\r\n");
      out.write("            //p564\r\n");
      out.write("            var str=\"\"\r\n");
      out.write("            $(\".uploadResult ul li\").each(function(idx, obj){\r\n");
      out.write("            	var jobj= $(obj)\r\n");
      out.write("            	console.dir(jobj)\r\n");
      out.write("            	var fileName= jobj.data('filename')\r\n");
      out.write("            	var uuid= jobj.data('uuid')            	\r\n");
      out.write("            	var path= jobj.data('path')\r\n");
      out.write("            	var type = jobj.data('type')\r\n");
      out.write("            	console.log(fileName, uuid, path, type)\r\n");
      out.write("            	str+= \"<input type='text' name='attachList[\"+idx+\"].fileName' value='\"+fileName+\"'>\"\r\n");
      out.write("				str+= \"<input type='text' name='attachList[\"+idx+\"].uuid' value='\"+uuid+\"'>\"\r\n");
      out.write("				str+= \"<input type='text' name='attachList[\"+idx+\"].uploadPath' value='\"+path+\"'>\"\r\n");
      out.write("				str+= \"<input type='text' name='attachList[\"+idx+\"].image' value='\"+type+\"'>\"\r\n");
      out.write("            })\r\n");
      out.write("            formObj.append(str).submit()\r\n");
      out.write("        })\r\n");
      out.write("        //p506\r\n");
      out.write("		var regex= new RegExp(\"(.*?)\\.(exe|sh|zip|alz)$\")//정규 표현식 공부 \r\n");
      out.write("		var maxSize= 5242880//5MB, 5x1024x1024 ,1k= 1024\r\n");
      out.write("		const checkExtension =(fileName ,fileSize)=>{\r\n");
      out.write("			if(fileSize>=maxSize){\r\n");
      out.write("				alert(\"파일 크기 초과\")\r\n");
      out.write("				return\r\n");
      out.write("			}\r\n");
      out.write("			if(regex.test(fileName)){\r\n");
      out.write("				alert(\"해당 종류의 파일은 업로드 할수 없어요\")\r\n");
      out.write("				return\r\n");
      out.write("			}\r\n");
      out.write("			return true\r\n");
      out.write("		}\r\n");
      out.write("		var cloneObj= $(\".uploadDiv\").clone()\r\n");
      out.write("		$(\".uploadResult\").on(\"click\",\"button\", function(e){\r\n");
      out.write("			console.log(\"삭제 버튼이 눌렸어요\")\r\n");
      out.write("			var targetFile =$(this).data(\"file\")\r\n");
      out.write("			var type= $(this).data(\"type\")\r\n");
      out.write("			console.log(targetFile)\r\n");
      out.write("			var targetLi = $(this).closest(\"li\")//가장 가까운  li 태그를 찾아라 \r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:'/deleteFile',\r\n");
      out.write("				data:{fileName:targetFile, type},\r\n");
      out.write("				dataType:'text',\r\n");
      out.write("				type:'post',\r\n");
      out.write("				success:function(result){\r\n");
      out.write("					alert(result)\r\n");
      out.write("					targetLi.remove()\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		})\r\n");
      out.write("		$(\"input[type='file']\").change(function(e){\r\n");
      out.write("			var formData= new FormData()\r\n");
      out.write("			var inputFile= $(\"input[name='uploadFile']\")\r\n");
      out.write("			var files= inputFile[0].files\r\n");
      out.write("			console.log(files)\r\n");
      out.write("			for (var i = 0; i < files.length; i++) {\r\n");
      out.write("				if(!checkExtension(files[i].name,files[i].size)) return false\r\n");
      out.write("				formData.append(\"uploadFile\",files[i])\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			var uploadResult= $(\".uploadResult ul\")\r\n");
      out.write("			//p537 참고\r\n");
      out.write("			const showUploadedFile=(uploadResultArr)=>{\r\n");
      out.write("				if(!uploadResultArr || uploadResultArr.length ==0) return\r\n");
      out.write("				var str=\"\"\r\n");
      out.write("				$(uploadResultArr).each(function(idx, obj){ //p525\r\n");
      out.write("					console.log(obj)\r\n");
      out.write("					if(obj.image) { // 이미지가 맞으면 아래 실행\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath+ \"/s_\"+obj.uuid+\"_\"+obj.fileName)\r\n");
      out.write("						var originPath = obj.uploadPath+ \"/\"+obj.uuid+\"_\"+obj.fileName\r\n");
      out.write("						originPath = originPath.replace(new RegExp(/\\\\/g), \"/\")  // \"\\\\\" => \"/\"  로 대체한다 (global)\r\n");
      out.write("						str+= \"<li data-path='\"+obj.uploadPath+\"'data-uuid='\"+obj.uuid+\"' data-fileName='\"\r\n");
      out.write("							+obj.fileName+\"'data-type='\"+obj.image+\"'\"\r\n");
      out.write("						str+= \"><div><span>\"+obj.fileName+\"</span><button type='button' data-file=\\'\"\r\n");
      out.write("							+fileCallPath+\"\\' data-type='image' \"\r\n");
      out.write("						str+= \"class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\"\r\n");
      out.write("						str+= \"<img src='/display?fileName=\" + fileCallPath +\"'></div></li>\"\r\n");
      out.write("					} else { // 이미지가 아니면 아래 실행\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath+ \"/\"+obj.uuid+\"_\"+obj.fileName)\r\n");
      out.write("						var fileLink = fileCallPath.replace(new RegExp(/\\\\/g), \"/\")\r\n");
      out.write("						str+= \"<li data-path='\"+obj.uploadPath+\"'data-uuid='\"+obj.uuid+\"' data-fileName='\"+obj.fileName+\r\n");
      out.write("						\"'data-type='\"+obj.image+\"'\"\r\n");
      out.write("						str+= \"><div><span>\"+obj.fileName+\"</span><button type='button' data-file=\\'\"\r\n");
      out.write("						+fileCallPath+\"\\' data-type='file' \"\r\n");
      out.write("						str+= \"class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button></br>\"\r\n");
      out.write("						str+= \"<img src='/resources/img/attach.jpg'></div></li>\"\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("				uploadResult.append(str)\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/uploadAjaxAction',\r\n");
      out.write("				processData: false,\r\n");
      out.write("				contentType: false,\r\n");
      out.write("				data: formData,\r\n");
      out.write("				type: 'POST',\r\n");
      out.write("				dataType: 'json',\r\n");
      out.write("				success: (result)=>{\r\n");
      out.write("					//alert(\"업로드 성공\")\r\n");
      out.write("					console.log(\"업로드 성공\", result)\r\n");
      out.write("					showUploadedFile(result) // 추가2\r\n");
      out.write("					//p521 , 이미지를 계속 반복해서 추가가능\r\n");
      out.write("					//$(\".uploadDiv\").html(cloneObj.html())\r\n");
      out.write("				}\r\n");
      out.write("			}) // ajax\r\n");
      out.write("		}) // button[type='file'] click\r\n");
      out.write("		$(\".uploadResult\").on(\"click\",\"button\", function(e) { ///// 변경\r\n");
      out.write("			console.log(\"이미지 삭제\")\r\n");
      out.write("			var targetFile = $(this).data('file')\r\n");
      out.write("			var type= $(this).data('type')\r\n");
      out.write("			console.log(targetFile)\r\n");
      out.write("			var targetLi = $(this).closest(\"li\")\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: '/deleteFile',\r\n");
      out.write("				data: {fileName: targetFile, type:type},\r\n");
      out.write("				dataType: 'text',\r\n");
      out.write("				type: 'POST',\r\n");
      out.write("				success: (result)=>{\r\n");
      out.write("					alert(result)\r\n");
      out.write("					targetLi.remove()\r\n");
      out.write("				}\r\n");
      out.write("			}) // ajax\r\n");
      out.write("		}) // uploadResult click\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <h1 class=\"page-header\">게시글 등록</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>		\r\n");
      out.write("            <!-- End of Main Content -->\r\n");
      out.write("            <!-- p239 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">게시글 등록</div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <form action=\"/board/register\" method=\"post\" role='form'>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"\">제목</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"title\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"\">내용</label>\r\n");
      out.write("                                    <textarea  id=\"\" class=\"form-control\" rows=\"5\" name=\"content\"></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"\">작성자</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"writer\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-default\">등록</button>\r\n");
      out.write("                                <button type=\"reset\" class=\"btn btn-default\">취소</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div> <!-- panel body-->\r\n");
      out.write("                    </div> <!-- panel-->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            파일 첨부\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\"form-group uploadDiv\">\r\n");
      out.write("                                <input type=\"file\" name=\"uploadFile\" multiple>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"uploadResult\">\r\n");
      out.write("                                <ul></ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> <!-- panel-body  -->\r\n");
      out.write("                    </div> <!-- panel-default  --> \r\n");
      out.write("                </div> <!-- col-lg-12  --> \r\n");
      out.write("            </div> <!-- row  -->  \r\n");
      out.write("            <!-- Footer -->\r\n");
      out.write("            <footer class=\"sticky-footer bg-white\">\r\n");
      out.write("                <div class=\"container my-auto\">\r\n");
      out.write("                    <div class=\"copyright text-center my-auto\">\r\n");
      out.write("                        <span>Copyright &copy; Your Website 2020</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- End of Footer -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Content Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Scroll to Top Button-->\r\n");
      out.write("    <a class=\"scroll-to-top rounded\" href=\"#page-top\">\r\n");
      out.write("        <i class=\"fas fa-angle-up\"></i>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Logout Modal-->\r\n");
      out.write("<!--     <div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("        aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">Ã</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <a class=\"btn btn-primary\" href=\"login.html\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("<!--     <script src=\"../resources/vendor/jquery/jquery.min.js\"></script> -->\r\n");
      out.write("    <script src=\"../resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"../resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"../resources/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"../resources/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"../resources/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"../resources/js/demo/datatables-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!--  êµì¬ p235 ì°½ì í¬ê¸°ë¥¼ ì¤ì¼ë ëª¨ë°ì¼ ííë¡ ì íëì´ì¼ í©ëë¤. -->\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$('#dataTables-example').DataTable({\r\n");
      out.write("				responsive: true\r\n");
      out.write("			});\r\n");
      out.write("			$(\".sidebar-nav\")\r\n");
      out.write("				.attr(\"class\",\"sidebar-nav navbar-collapse collapse\")\r\n");
      out.write("				.attr(\"aria-expanded\",'false')\r\n");
      out.write("				.attr(\"style\",\"height:1px\");\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
